### ISSUE TITLE
資料定義問題 w/READr「開放人物關係資料庫」計畫

### ISSUE THREAD

**Issue by tynnie** [ptstaiwan/pts-data#2]
1.【人】資料庫
[檔案連結](https://github.com/ptstaiwan/pts-data/blob/master/election_data/people_db.csv)
欄位： `name, gender, date of birth, source`
主要問題：舊名處理原則、生日如果出錯校正方式
說明：
* 目前沒有附上舊名。如果需要附上舊名，想討論以哪個版本為主。
    * 舊名目前只有處理原住民的姓名，原住民的姓名以最新一次選舉登記的名稱為主，舊名可能有好幾個版本，這邊想討論是都要一並列出嗎？例如
![螢幕快照 2020-09-28 上午12 56 15](https://user-images.githubusercontent.com/30755520/94371459-54078d00-0129-11eb-96c9-8dc0e798d10c.png)

        那舊名就是`侯金助 Kuljelje・Gadugadu, 侯金助 Kuljelje・gadugadu, 侯金助`?
        還是想要怎麼處理？因為以最新的那一個舊名好像也怪怪的，上次討論到大寫小寫可能因他們的共識而定，因此沒有特別做處理，也因為這樣會有好幾個版本的名字⋯⋯
* 生日的校正也會影響到名字的校正。在還沒有校正生日的狀況下，這份資料庫共有42914筆候選人的資料，其中5321筆姓名、性別一樣，出生年份不一樣。
	* 初步查閱後，有些人是同名同姓，確實是不同人；但有些是同一個人但出生年份登記錯誤，還在想這個要怎麼辦⋯⋯
	* 這邊會影響名字的校正，是因為處理名字的過濾機制，也是拿生日當篩選標準，因此生日有錯，名字的過濾也會出錯，相關處理也會有誤差

2.【人與選舉】資料庫（併了議員、還沒有做不分區）
[檔案連結](https://github.com/ptstaiwan/pts-data/blob/master/election_data/election_db_with_ccm.csv)
欄位：`姓名,生理性別,出生日期,選舉年,選舉名稱,號次,選區,得票數,得票率,是否當選,是否現任,資料來源`
主要問題：要不要「性別」欄位、需要資料庫欄位名稱
說明：
- 雖然格式沒有要求性別，這邊還是先附上，方便後續mapping（如果不需要再告知，可以拿掉）
* 生日同樣還沒有debug。
* 原住民的姓名都是最新的。
* 我看文件上有標註後端資料欄位的名稱，但是【人與選舉】資料庫好像還沒做，可以的話希望先拿到，不然之後再換掉也可以

**Comment by azoezoe** [comment]
1. 舊名要全部列出
是 `侯金助 Kuljelje・Gadugadu,侯金助 Kuljelje・gadugadu,侯金助`
逗號前後不要空格

2. 同名生日有誤的可以查[這裡](http://bulletin.cec.gov.tw)
如果還是有誤的話，就查資料，再另外列一張校正表

3. 人跟選舉先不要做

**Comment by tynnie** [comment]
@azoezoe  同名生日的困難點在於難分辨是錯誤（同一個人）還是剛好同名同姓（不同人）～其他收到

**Comment by azoezoe** [comment]
就只能手動查證囉
